project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Majors"
  page-footer:
    left: "espejo@upenn.edu"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
  sidebar:
    logo: "images/A&S.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: Fields of Study
        contents:
          - Majors/Africana.ipynb
          - Majors/Anthropology.ipynb
          - Majors/ArtHistory.ipynb
          - Majors/Biology.ipynb
          - Majors/Chemistry.ipynb
          - Majors/Cinema.ipynb
          - Majors/Classics.ipynb
          - Majors/Criminology.ipynb
          - Majors/EarthandE.ipynb
          - Majors/EastAsian.ipynb
          - Majors/Economics.ipynb
          - Majors/English.ipynb
          - Majors/FIGS.ipynb
          - Majors/History.ipynb
          - Majors/HistoryAndSoc.ipynb
          - Majors/Linguistics.ipynb
          - Majors/Mathematics.ipynb
          - Majors/MiddleEastern.ipynb
          - Majors/Music.ipynb
          - Majors/Philosophy.ipynb
          - Majors/PhysicsAndAstronomy.ipynb
          - Majors/PoliticalScience.ipynb
          - Majors/ReligiousStudies.ipynb
          - Majors/Sociology.ipynb
          - Majors/SouthAsianStudies.ipynb
          - Majors/SpanishAndPortugese.ipynb
        
          

format:
  html:
    highlight-style: solarized
    theme: default
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
