project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Majors"
  page-footer:
    left: "espejo@upenn.edu"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
  sidebar:
    logo: "images/A&S.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: Majors
        contents:
          - Majors/Africana.ipynb

format:
  html:
    highlight-style: solarized
    theme: default
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
